export const enums = {
    ADD_TODO: 'ADD_TODO'
    , DELETE_TODO: 'DELETE_TODO'
    , COMPLETE_TODO_ALL: 'COMPLETE_TODO_ALL'
    , COMPLETE: 'COMPLETE_TODO'
    ,TO_DO_LIST:'TO_DO_LIST'
    ,INCREMENT:'INCREMENT'
    ,DECREMENT:'DECREMENT'
    ,RESET:'RESET'
}